### ISSUE TITLE
Multiple logins

### ISSUE THREAD

**Issue by billray0259** [mua2010/PEPro#4]
When the same user is logged-in in multiple places it is possible to accept a request twice and have two drafts to the same person.

**Comment by billray0259** [comment]
This needs to be tested but I think it has been fixed by checking to make the sure status of the request is pending before creating another draft.

**Comment by mua2010** [comment]
Correct!
Also, we needed to catch the exception and return feedback instead of letting the code go into the block where review object is created.
**You can see the response shown in the pic below**

![image](https://user-images.githubusercontent.com/33365875/79543947-3a332b80-805c-11ea-8d4e-979140caa3a3.png)
